#----------------------------------------------------------------------------
# The file contains general metadata for the project.
#----------------------------------------------------------------------------
type:               project
title:              Crossword Designer
version:            100